ALTER TABLE "payroll_records"
  ADD COLUMN "senaEmployer" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "icbfEmployer" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "healthBase" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "pensionBase" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "arlBase" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "compensationBase" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "senaBase" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "icbfBase" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "socialSecuritySnapshot" JSONB;

ALTER TABLE "payroll_policies"
  ADD COLUMN "minimumWageValue" DECIMAL(12,2) NOT NULL DEFAULT 1300000,
  ADD COLUMN "senaRate" DECIMAL(8,4) NOT NULL DEFAULT 0.02,
  ADD COLUMN "icbfRate" DECIMAL(8,4) NOT NULL DEFAULT 0.03,
  ADD COLUMN "healthCapSmmlv" DECIMAL(8,2) NOT NULL DEFAULT 25,
  ADD COLUMN "pensionCapSmmlv" DECIMAL(8,2) NOT NULL DEFAULT 25,
  ADD COLUMN "parafiscalCapSmmlv" DECIMAL(8,2) NOT NULL DEFAULT 25,
  ADD COLUMN "applySena" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "applyIcbf" BOOLEAN NOT NULL DEFAULT true;
